name: Playwright Tests

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  playwright-tests:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand(\"ping\").ok' --quiet"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      NODE_ENV: testing
      MONGO_URL: mongodb://localhost:27017/test-db

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23'

      - name: Install backend dependencies
        run: npm install

      - name: Install frontend dependencies
        working-directory: ./client
        run: npm install

      - name: Install Playwright Browsers
        working-directory: ./client
        run: npx playwright install --with-deps

      - name: Start Backend & Frontend
        run: |
          npm run dev &                
          sleep 10              

      - name: Run Playwright tests
        run: npx playwright test

